sudo: required
services:
- docker

language: node_js
node_js:
  - "8"

install: yarn
script:
  - yarn lint
  - yarn test

#after_success:
#  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then bin/docker-build-and-deploy.sh; fi
